name: Daily Branch Cleanup

on:
  workflow_dispatch:
  #schedule:
    #- cron: '* * * * *' # 毎日0時に実行

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete branches
        run: |
          git fetch origin
          TWO_WEEKS_AGO=$(date -d "12 hours ago" +%s)
          for branch in $(git branch -r | grep 'origin/deploy/int' | sed 's/origin\///'); do
            echo $branch
            echo $(git show -s --format="%ci" "$branch")
            echo $(git show -s --format="%ci" "$branch" | head -n 1)
            LAST_COMMIT_DATE=$(git show -s --format="%ci" $branch | head -n 1)
            LAST_COMMIT_DATE_EPOCH=$(date -d "$LAST_COMMIT_DATE" +%s)
            echo $LAST_COMMIT_DATE
            echo $LAST_COMMIT_DATE_EPOCH
            echo $TWO_WEEKS_AGO

            if [ $LAST_COMMIT_DATE_EPOCH -lt $TWO_WEEKS_AGO ]; then
              git push origin --delete $branch
            fi
          done
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
